# Day 52 — TensorFlow Intro: Variables and Data Structures
- Understand what TensorFlow is and how tensors work.
- Create tensors and inspect their shape, rank, and data type.
- Use TensorFlow operations in a NumPy-like way.
- Convert between TensorFlow tensors and NumPy arrays.
- Understand TensorFlow type conversions.
- Create and update `tf.Variable` objects.
- Work with TensorFlow strings.
- Understand ragged tensors and sparse tensors.
- Recognize other TensorFlow data structures.
- Understand why these structures matter for neural-network training.

## 1. Import TensorFlow and NumPy

TensorFlow is primarily a numerical-computing framework designed for machine learning. Its basic numerical object is a **tensor**.

A tensor is similar to a NumPy array, but TensorFlow tensors can be efficiently processed on CPUs, GPUs, and other accelerators and can participate in automatic differentiation.


In [1]:
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)
print("NumPy version:", np.__version__)


TensorFlow version: 2.21.0
NumPy version: 2.4.6


## 2. What is a Tensor?

A tensor is a multidimensional array.

Examples:

- **Scalar:** rank 0 → `42`
- **Vector:** rank 1 → `[1, 2, 3]`
- **Matrix:** rank 2 → `[[1, 2], [3, 4]]`
- **Higher-dimensional tensor:** rank 3 or more

The three properties you should always remember are:

```text
rank  → number of dimensions
shape → size along each dimension
dtype → data type of elements
```


In [2]:
scalar = tf.constant(42)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for name, x in [
    ("scalar", scalar),
    ("vector", vector),
    ("matrix", matrix),
    ("tensor_3d", tensor_3d)
]:
    print(f"{name}:")
    print(" value:", x)
    print(" rank :", tf.rank(x).numpy())
    print(" shape:", x.shape)
    print(" dtype:", x.dtype)
    print()


scalar:
 value: tf.Tensor(42, shape=(), dtype=int32)
 rank : 0
 shape: ()
 dtype: <dtype: 'int32'>

vector:
 value: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
 rank : 1
 shape: (3,)
 dtype: <dtype: 'int32'>

matrix:
 value: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
 rank : 2
 shape: (2, 2)
 dtype: <dtype: 'int32'>

tensor_3d:
 value: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
 rank : 3
 shape: (2, 2, 2)
 dtype: <dtype: 'int32'>



## 3. Creating Tensors

TensorFlow provides many functions that feel familiar if you know NumPy.

Common functions:

- `tf.zeros()`
- `tf.ones()`
- `tf.fill()`
- `tf.range()`
- `tf.eye()`
- `tf.random.normal()`
- `tf.random.uniform()`


In [3]:
zeros = tf.zeros((2, 3))
ones = tf.ones((2, 3))
filled = tf.fill((2, 3), 7)
sequence = tf.range(0, 10, delta=2)
identity = tf.eye(3)

print("Zeros:\n", zeros.numpy())
print("\nOnes:\n", ones.numpy())
print("\nFilled:\n", filled.numpy())
print("\nRange:", sequence.numpy())
print("\nIdentity:\n", identity.numpy())


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Filled:
 [[7 7 7]
 [7 7 7]]

Range: [0 2 4 6 8]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 4. Tensor Shape and Reshaping

A tensor's shape tells us how many elements exist along each dimension.

For example:

```text
shape = (2, 3, 4)
```

means:

- 2 blocks
- 3 rows per block
- 4 values per row

`tf.reshape()` changes the organization of the tensor without changing the number of elements.


In [4]:
x = tf.range(24)

print("Original:")
print(x)
print("Shape:", x.shape)

x_2d = tf.reshape(x, (6, 4))
x_3d = tf.reshape(x, (2, 3, 4))

print("\n6 x 4:")
print(x_2d.numpy())

print("\n2 x 3 x 4:")
print(x_3d.numpy())


Original:
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)
Shape: (24,)

6 x 4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

2 x 3 x 4:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 5. Indexing and Slicing

TensorFlow tensors support NumPy-like indexing and slicing.

Examples:

```python
x[0]
x[:, 1]
x[1:3]
x[..., -1]
```


In [5]:
x = tf.constant([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("x:\n", x.numpy())

print("\nFirst row:", x[0].numpy())
print("Second column:", x[:, 1].numpy())
print("Rows 1 onward:\n", x[1:].numpy())
print("Last column:", x[..., -1].numpy())


x:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

First row: [10 20 30]
Second column: [20 50 80]
Rows 1 onward:
 [[40 50 60]
 [70 80 90]]
Last column: [30 60 90]


## 6. TensorFlow Operations

TensorFlow provides operations for arithmetic, linear algebra, reductions, comparisons, and more.

Common examples:

- `tf.add`
- `tf.subtract`
- `tf.multiply`
- `tf.divide`
- `tf.square`
- `tf.sqrt`
- `tf.maximum`
- `tf.reduce_sum`
- `tf.reduce_mean`
- `tf.matmul`


In [6]:
a = tf.constant([[1., 2.], [3., 4.]])
b = tf.constant([[5., 6.], [7., 8.]])

print("Addition:\n", tf.add(a, b).numpy())
print("\nElement-wise multiplication:\n", tf.multiply(a, b).numpy())
print("\nSquare of a:\n", tf.square(a).numpy())
print("\nMean of a:", tf.reduce_mean(a).numpy())
print("Sum of a:", tf.reduce_sum(a).numpy())

print("\nMatrix multiplication:")
print(tf.matmul(a, b).numpy())


Addition:
 [[ 6.  8.]
 [10. 12.]]

Element-wise multiplication:
 [[ 5. 12.]
 [21. 32.]]

Square of a:
 [[ 1.  4.]
 [ 9. 16.]]

Mean of a: 2.5
Sum of a: 10.0

Matrix multiplication:
[[19. 22.]
 [43. 50.]]


## 7. TensorFlow Operators Look Like NumPy

TensorFlow also overloads Python operators, so you can often write:

```python
a + b
a * b
a / b
a ** 2
```

instead of explicitly calling `tf.add()`, `tf.multiply()`, etc.

This makes TensorFlow code feel very similar to NumPy.


In [7]:
a = tf.constant([[1., 2.], [3., 4.]])
b = tf.constant([[10., 20.], [30., 40.]])

print("a + b:\n", (a + b).numpy())
print("\na * b:\n", (a * b).numpy())
print("\na / 2:\n", (a / 2).numpy())
print("\na ** 2:\n", (a ** 2).numpy())


a + b:
 [[11. 22.]
 [33. 44.]]

a * b:
 [[ 10.  40.]
 [ 90. 160.]]

a / 2:
 [[0.5 1. ]
 [1.5 2. ]]

a ** 2:
 [[ 1.  4.]
 [ 9. 16.]]


## 8. Broadcasting

TensorFlow follows NumPy-style broadcasting rules.

For example, a matrix with shape `(2, 3)` can be added to a vector with shape `(3,)`.

The vector is conceptually broadcast across the rows.


In [8]:
matrix = tf.constant([
    [1., 2., 3.],
    [4., 5., 6.]
])

bias = tf.constant([10., 20., 30.])

result = matrix + bias

print("Matrix shape:", matrix.shape)
print("Bias shape:", bias.shape)
print("\nResult:")
print(result.numpy())


Matrix shape: (2, 3)
Bias shape: (3,)

Result:
[[11. 22. 33.]
 [14. 25. 36.]]


## 9. TensorFlow and NumPy

TensorFlow and NumPy work together very well.

### NumPy → TensorFlow

```python
tf.constant(numpy_array)
```

### TensorFlow → NumPy

```python
tensor.numpy()
```

One important distinction is that TensorFlow tensors are designed to participate in TensorFlow's computation and automatic differentiation system, while NumPy arrays are NumPy objects.


In [9]:
numpy_array = np.array([[1, 2], [3, 4]], dtype=np.float32)

tensor = tf.constant(numpy_array)
back_to_numpy = tensor.numpy()

print("NumPy array:")
print(numpy_array)
print("Type:", type(numpy_array))

print("\nTensorFlow tensor:")
print(tensor)
print("Type:", type(tensor))

print("\nBack to NumPy:")
print(back_to_numpy)
print("Type:", type(back_to_numpy))


NumPy array:
[[1. 2.]
 [3. 4.]]
Type: <class 'numpy.ndarray'>

TensorFlow tensor:
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Type: <class 'tensorflow.python.framework.ops.EagerTensor'>

Back to NumPy:
[[1. 2.]
 [3. 4.]]
Type: <class 'numpy.ndarray'>


## 10. Type Conversions

TensorFlow is more strict about data types than Python can sometimes appear to be.

For example, mixing `float32` and `float64` tensors may cause errors in operations where matching dtypes are required.

Use `tf.cast()` when you intentionally need to convert a tensor's dtype.


In [10]:
x = tf.constant([1, 2, 3], dtype=tf.int32)

x_float = tf.cast(x, tf.float32)
x_float64 = tf.cast(x, tf.float64)

print("Original:", x, x.dtype)
print("float32:", x_float, x_float.dtype)
print("float64:", x_float64, x_float64.dtype)


Original: tf.Tensor([1 2 3], shape=(3,), dtype=int32) <dtype: 'int32'>
float32: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32) <dtype: 'float32'>
float64: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64) <dtype: 'float64'>


## 11. TensorFlow Variables

This is one of the most important topics of this day.

A `tf.Tensor` is generally treated as an immutable value.

A `tf.Variable` is a mutable state container.

Neural networks need mutable state because model parameters such as **weights and biases must be updated during training**.

Typical pattern:

```python
weight = tf.Variable(initial_value)
weight.assign(new_value)
```

During training, an optimizer repeatedly updates variables to reduce the loss.


In [11]:
weight = tf.Variable([1.0, 2.0, 3.0])

print("Initial weight:", weight.numpy())

weight.assign([10.0, 20.0, 30.0])

print("After assign:", weight.numpy())


Initial weight: [1. 2. 3.]
After assign: [10. 20. 30.]


## 12. `assign_add()` and `assign_sub()`

Variables support convenient in-place-style updates:

```python
variable.assign_add(...)
variable.assign_sub(...)
```

These are useful for counters and model parameters.


In [12]:
counter = tf.Variable(0)

print("Initial:", counter.numpy())

counter.assign_add(5)
print("After +5:", counter.numpy())

counter.assign_sub(2)
print("After -2:", counter.numpy())


Initial: 0
After +5: 5
After -2: 3


## 13. Why Variables Matter in Neural Networks

A simplified neural-network training step looks conceptually like this:

```text
Input X
   ↓
Weights W + Bias b
   ↓
Prediction
   ↓
Loss
   ↓
Gradients
   ↓
Optimizer
   ↓
Update W and b
```

`W` and `b` are TensorFlow variables.

For example:

```python
W = tf.Variable(...)
b = tf.Variable(...)
```

The optimizer modifies these variables repeatedly during training.


In [13]:
# A tiny manually-updated linear model

W = tf.Variable(0.0)
b = tf.Variable(0.0)

x = tf.constant(2.0)
y = tf.constant(10.0)

learning_rate = 0.1

prediction = W * x + b
loss = (prediction - y) ** 2

print("Initial W:", W.numpy())
print("Initial b:", b.numpy())
print("Prediction:", prediction.numpy())
print("Loss:", loss.numpy())


Initial W: 0.0
Initial b: 0.0
Prediction: 0.0
Loss: 100.0


## 14. TensorFlow Strings

TensorFlow also has a string tensor type.

Strings are not ordinary numerical tensors, but TensorFlow provides operations for processing them, especially in data pipelines.


In [14]:
text = tf.constant(["TensorFlow", "Machine Learning", "Python"])

print(text)
print("dtype:", text.dtype)

lower = tf.strings.lower(text)
print("\nLowercase:")
print(lower.numpy())

lengths = tf.strings.length(text)
print("\nString lengths:")
print(lengths.numpy())


tf.Tensor([b'TensorFlow' b'Machine Learning' b'Python'], shape=(3,), dtype=string)
dtype: <dtype: 'string'>

Lowercase:
[b'tensorflow' b'machine learning' b'python']

String lengths:
[10 16  6]


## 15. Ragged Tensors

A normal tensor requires a rectangular shape.

But real-world data may have different numbers of elements per row.

Example:

```text
[10, 20]
[30, 40, 50]
[60]
```

This cannot naturally be represented by a regular rectangular tensor without padding.

A **ragged tensor** allows rows to have different lengths.

This is useful for variable-length sequences such as:

- sentences with different numbers of words
- user histories
- sequences of events


In [15]:
ragged = tf.ragged.constant([
    [10, 20],
    [30, 40, 50],
    [60]
])

print(ragged)
print("\nRow 0:", ragged[0].numpy())
print("Row 1:", ragged[1].numpy())
print("Row 2:", ragged[2].numpy())

print("\nRow lengths:", ragged.row_lengths().numpy())


<tf.RaggedTensor [[10, 20], [30, 40, 50], [60]]>

Row 0: [10 20]
Row 1: [30 40 50]
Row 2: [60]

Row lengths: [2 3 1]


## 16. Sparse Tensors

A sparse tensor is useful when most values are zero.

Instead of storing every zero, TensorFlow can store only the non-zero values and their locations.

Example:

```text
0 0 0 5
0 0 0 0
0 7 0 0
```

This can save memory when tensors are extremely sparse.

Sparse tensors are common in areas such as:

- recommendation systems
- text processing
- large categorical features
- graph-like data


In [16]:
sparse = tf.sparse.SparseTensor(
    indices=[[0, 3], [2, 1]],
    values=[5, 7],
    dense_shape=[3, 4]
)

print("Sparse tensor:")
print(sparse)

print("\nDense representation:")
print(tf.sparse.to_dense(sparse).numpy())


Sparse tensor:
SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([5 7], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

Dense representation:
[[0 0 0 5]
 [0 0 0 0]
 [0 7 0 0]]


## 17. TensorArray

`tf.TensorArray` is a TensorFlow data structure designed for storing tensors dynamically, especially inside TensorFlow control-flow operations.

You will encounter it less frequently in everyday Keras code, but it is useful to recognize the concept.

For many standard ML workflows, ordinary tensors, variables, ragged tensors, and sparse tensors are more important.


In [17]:
ta = tf.TensorArray(dtype=tf.float32, size=3)

ta = ta.write(0, 10.0)
ta = ta.write(1, 20.0)
ta = ta.write(2, 30.0)

print("TensorArray values:")
print(ta.stack().numpy())


TensorArray values:
[10. 20. 30.]


## 18. TensorFlow Sets

TensorFlow also has support for set-like operations.

These can be useful when working with unique categorical values or membership operations.


In [18]:
a = tf.constant([1, 2, 3, 3])
b = tf.constant([3, 4, 5])

unique_a = tf.unique(a).y

print("Unique values in a:", unique_a.numpy())

set_result = tf.sets.union(
    tf.reshape(a, (1, -1)),
    tf.reshape(b, (1, -1))
)

print("\nUnion:")
print(tf.sparse.to_dense(set_result).numpy())


Unique values in a: [1 2 3]

Union:
[[1 2 3 4 5]]


## 19. TensorFlow vs NumPy — Quick Comparison

| Concept | NumPy | TensorFlow |
|---|---|---|
| Main array type | `ndarray` | `Tensor` |
| Mutable parameter container | — | `tf.Variable` |
| GPU/accelerator support | Limited/general ecosystem | Built into TensorFlow |
| Automatic differentiation | No | Yes |
| ML model training | External libraries | Core capability |
| Ragged data | Usually custom/object approaches | `tf.RaggedTensor` |
| Sparse data | Sparse libraries | `tf.sparse` |

The important point is not that TensorFlow replaces NumPy.

Instead:

```text
NumPy       → general numerical computing
TensorFlow  → numerical computing + differentiation + ML training
```


# 20. Mini Exercise — TensorFlow Like NumPy

Try solving this without looking at the solution first.

Create a TensorFlow tensor containing:

```text
1, 2, 3, ..., 12
```

Then:

1. Reshape it into `(3, 4)`.
2. Multiply every value by 2.
3. Calculate the mean of the entire tensor.
4. Calculate the sum of each row.
5. Calculate the sum of each column.
6. Convert the final tensor to NumPy.


In [19]:
# YOUR CODE HERE

x = tf.range(1, 13)
x = tf.reshape(x, (3, 4))

doubled = x * 2
mean_value = tf.reduce_mean(doubled)
row_sums = tf.reduce_sum(doubled, axis=1)
column_sums = tf.reduce_sum(doubled, axis=0)

print("Tensor:\n", x.numpy())
print("\nDoubled:\n", doubled.numpy())
print("\nMean:", mean_value.numpy())
print("\nRow sums:", row_sums.numpy())
print("Column sums:", column_sums.numpy())
print("\nNumPy type:", type(doubled.numpy()))


Tensor:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Doubled:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Mean: 13

Row sums: [20 52 84]
Column sums: [30 36 42 48]

NumPy type: <class 'numpy.ndarray'>


# 21. Mini Exercise — TensorFlow Variable

Create a variable:

```python
w = tf.Variable([1., 2., 3.])
```

Then:

1. Add 10 to every value.
2. Subtract 2 from every value.
3. Replace the values with `[100., 200., 300.]`.


In [21]:
# YOUR CODE HERE

w = tf.Variable([1., 2., 3.])

w.assign_add([10., 10., 10.])
print("After adding 10:", w.numpy())

w.assign_sub([2., 2., 2.])
print("After subtracting 2:", w.numpy())

w.assign([100., 200., 300.])
print("After assign:", w.numpy())


After adding 10: [11. 12. 13.]
After subtracting 2: [ 9. 10. 11.]
After assign: [100. 200. 300.]
